# Start with pre-built Greengrass docker image
# NOTE: Change the version value in greengrass-entrypoint.sh to reference same version
FROM amazon/aws-iot-greengrass:1.10.2-amazonlinux-x86-64

# Install system dependencies and supporting services for accelerator
# and then clear caches to reduce layer/image size
RUN rm -rf /var/cache/amzn2extras

# Add python packages from requirements.txt
ADD requirements.txt /
WORKDIR /
RUN pip3.7 install -r requirements.txt

# Replace entrypoint with one specific for the accelerator
COPY greengrass-entrypoint.sh /